# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dlsapient-patch-1 ]
  pull_request:
    branches: [ dlsapient-patch-1 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build0:
#     runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        node-version: [8.x] # , 10.x, 12.x
        os: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      - name: test run
        run: |
          echo 'this is a test run on ${{ matrix.os }}'
          ls -l
          
      # Run Linter against code base
      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
        
      
    

# #   This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
#     needs: [build0]

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: |
#           echo Hello, world!
#           ls -a

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
