# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-18.04
    environment:
      name: dev
      url: 'http://dev.myapp.com'
    steps:
      - name: development
        run: |
          echo I am in dev environment
      

  build:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2
      - name: test run
        run: |
          echo 'this is a test run on ubuntu-latest'
          ls -l
          
      # Run Linter against code base
      
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
